import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "audiophile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <StoreProvider>
          <ToastContainer
            pauseOnFocusLoss={false}
            autoClose={3000}
          />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
